/**
 * Generate the local MCP client config.
 *
 * Responsibility: write `foundation-lab-mcp.json`, the file passed to
 * `claude --mcp-config`, pointing at this repository's own MCP server.
 *
 * Place in the system: a script, not application code.
 *
 * Why generated rather than committed: the file carries a credential VALUE — the LOCAL seed
 * password the MCP server signs in with. The repository stores secret references, never
 * values (SPEC §7), so the generated file is gitignored. The values are LOCAL-only
 * throwaways against synthetic data, but committing a password shaped like a real one is
 * exactly what the Phase 13 secret-exposure audit should catch, so it is not committed.
 *
 * Run `node scripts/seed-local.ts` first — the credential below must exist.
 */

import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { loadConfig } from '../src/spine/config.ts';

const config = loadConfig();

if (config.environment !== 'LOCAL') {
  console.error(`Refusing to write an MCP config for ${config.environment}. This script is LOCAL only.`);
  process.exit(1);
}

const REPOSITORY = resolve(import.meta.dirname, '..');
const OUTPUT = resolve(REPOSITORY, 'foundation-lab-mcp.json');

/** Must match `scripts/seed-local.ts`. The MCP server acts as this one user and no other. */
const MCP_IDENTITY = { email: 'ana@acme.test', password: 'acme-local-password' };

const contents = {
  $comment:
    'Generated by scripts/write-mcp-config.ts. Pass with --mcp-config AND keep '
    + '--strict-mcp-config: without the strict flag the session also picks up the other '
    + 'configured servers, including claude.ai connectors and a work-plane admin gateway.',
  mcpServers: {
    'foundation-lab': {
      command: 'node',
      args: [resolve(REPOSITORY, 'src/spine/mcp-main.ts')],
      env: {
        FL_DATABASE_PATH: resolve(REPOSITORY, 'data/foundation-lab.local.sqlite'),
        FL_OTLP_ENDPOINT: config.otlpEndpoint,
        // Fixed, so sessions survive a server restart. LOCAL only; DEV and SANDBOX refuse
        // to start without a secret supplied from the configured backend.
        FL_SESSION_SECRET: 'local-mcp-development-secret',
        FL_MCP_EMAIL: MCP_IDENTITY.email,
        FL_MCP_PASSWORD: MCP_IDENTITY.password,
      },
    },
  },
};

writeFileSync(OUTPUT, `${JSON.stringify(contents, null, 2)}\n`);
console.log(`wrote ${OUTPUT}`);
console.log(`the MCP server will act as ${MCP_IDENTITY.email} and cannot become another user`);
